Test file for the class BaseGeometry in 7-base_geometry.py
=====================================================================

Module ``class``
---------------------

Import the function:
    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

-----------------------------
-----------------------------
Public instance method: integer_validator()
    >>> "integer_validator" in dir(BaseGeometry)
    True

Public instance method: area()

    >>> "area" in dir(BaseGeometry)
    True

-----------------------------
-----------------------------
Checking area exception

    >>> figure = BaseGeometry()
    >>> figure.area()
    Traceback (most recent call last):
    Exception: area() is not implemented

-----------------------------
-----------------------------
Value is not an integer

    >>> figure.integer_validator('width', 'Jhon')
    Traceback (most recent call last):
    ...
    TypeError: width must be an integer

    >>> figure.integer_validator('width', 3.45)
    Traceback (most recent call last):
    ...
    TypeError: width must be an integer

    >>> figure.integer_validator('width', [1, 2])
    Traceback (most recent call last):
    ...
    TypeError: width must be an integer

    >>> figure.integer_validator('width', (3, ))
    Traceback (most recent call last):
    ...
    TypeError: width must be an integer

    >>> figure.integer_validator('width', 'c')
    Traceback (most recent call last):
    ...
    TypeError: width must be an integer

    >>> figure.integer_validator('width', True)
    Traceback (most recent call last):
    ...
    TypeError: width must be an integer

    >>> figure.integer_validator('width', None)
    Traceback (most recent call last):
    ...
    TypeError: width must be an integer

-----------------------------
-----------------------------
Value is less or equal to 0

    >>> figure.integer_validator('width', 0)
    Traceback (most recent call last):
    ...
    ValueError: width must be greater than 0

    >>> figure.integer_validator('width', -8)
    Traceback (most recent call last):
    ...
    ValueError: width must be greater than 0

-----------------------------
-----------------------------
Incorrect amount of arguments.

    >>> figure.integer_validator('width')
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'

    >>> figure.integer_validator()
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

    >>> figure.integer_validator('width', 5, 56)
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() takes 3 positional arguments but 4 were given
